### DISCUSSION TITLE
Custom background text visibility.

### DISCUSSION THREAD

**Discussion by h3canlao** [Eight-P/BetterDiscord-Stuff#40] [General]
![image](https://github.com/user-attachments/assets/fbbbd08f-4d1a-4bee-8904-0400bb9cdd0a)
![image](https://github.com/user-attachments/assets/7700d18f-486b-4f54-8bb1-6ca645129d63)

Is there any way to make these components stand out more or change the color so they are easier to see :(.
Like this:
![image](https://github.com/user-attachments/assets/de729a90-1e24-44bd-9191-f1c399a40fe0)
and:
![image](https://github.com/user-attachments/assets/d42f8b2e-f71a-4b40-9794-3a59713e8c9a)

**Comment by Eight-P** [comment]
I would love to offer more color customization at some point, 
but that is something for a rework in the future.
As it is right now, the theme is mostly designed for the default background, 
and other images, unfortunately might just not always work that well as a background.

**Comment by Eight-P** [comment]
You could add this to your theme file or custom css and play around with the colors, but it might not be great.

```css
html.theme-dark:root, #app-mount .theme-dark {
  --channels-default: white !important ;

  --interactive-normal: white  !important ; 
  --interactive-hover: white !important ;
  --interactive-active: white !important ;
  --interactive-muted: lightgray !important ;

  --text-normal: white !important;
  --text-muted: lightgray !important;

  --text-primary: white !important ;
  --text-secondary: white !important ;
  --text-tertiary: white !important ;

  --header-primary: white !important ;
  --header-secondary: white !important ;
}
```
