### DISCUSSION TITLE
Is it possible to implement the DM highlight style in channels as well

### DISCUSSION THREAD

**Discussion by neuro-stitch** [Eight-P/BetterDiscord-Stuff#43] [Q&A]
Channels in servers use the typical unread dot instead of the sleek bar design of DMs you're currently in. Is there a way to make it consistent with the DMs?

**Comment by Eight-P** [comment]
The white border, like on DMs is more of an extension of the hover effect and currently selected indicator, while the dot in the channels list is an indication of unread messages (same in the server bar) so I'd rather not mix them up because they serve different purposes.

**Reply by neuro-stitch** [reply]
Ahh understandable! Would it still be possible to get that hover effect in the channels though, or would that conflict with the unread dots?

**Reply by Eight-P** [reply]
I don't know, I'm not sure if I see a way that I like.

This would kind of work.
![Screenshot 2025-05-14 155836](https://github.com/user-attachments/assets/9048976f-e64e-4289-880a-bf9f9b4ff340)

But I haven't been a huge fan of that border in general for a while now.
It only works well when it's at the edge of the app.
I already dropped it in the settings panel.
And since win11 cuts off 1 or 2 pixels from the app when in window mode, it only really got worse.
![Screenshot 2025-05-14 161521](https://github.com/user-attachments/assets/1e64ab3f-87c5-471f-9d22-6a109ed4d085)

**Reply by neuro-stitch** [reply]
Oh yeah windows 11 window mode leaves much to be desired ack
Honestly though to me I really like the border, I customized the theme and the way I had it really looked good haha
Would it be possible to at least get the code to do that so I can play around with it on my copy of the theme? if not that's totally fine, I'm just curious! I'm running windows 10 so the windows 11 mode won't bother me ^-^
Also so sorry for the late reply! It's been a busy week.

**Reply by Eight-P** [reply]
sure
```css
#app-mount .wrapper__2ea32 {
  margin: 0 ;

  & .unread__2ea32 {
    margin-top: -3px ;
    height: 6px ;
    width: 6px ;
    left: 33px;
    border-radius: 50% ;
    background-color: var(--interactive-hover);

    & + div .iconContainer__2ea32 {
      margin-right: 8px ;
    }
  }

  & .link__2ea32 {
    padding: 2px 8px ;
    margin: 2px 0 ;
    border-left: 3px solid transparent ;
    border-radius: 0 ;

    &:hover {
      border-color: var(--interactive-hover);
      background-color: var(--background-modifier-hover);
    }
  }

  &:is(.modeSelected__2ea32, .modeConnected__2ea32) {
    & .link__2ea32 {
      border-color: var(--interactive-hover);
    }
    & .icon__2ea32 {
      /* color: var(--channels-default) !important; */ 
    }
  }
}
```
I mean, I've kinda just thrown this together to see how it would look.
Didn't really do much testing.
And of course there is always a chance Discord breaks it again.
